print("Naaminvoer")
name = input("geef jouw naam")
print("Adresnvoer")
adres = input("geef jouw adres")
print("Postcode  invoer")
Postcode = input("geef jouw Postcode")
print("Woonplaats")
Woonplaats = input("geef jouw woonplaats")

print("----------------------------------------------------")
print("|  Naam      :" + name)
print("|  Adres     :" + adres)
print("|  Postcode  :" + Postcode )
print("|  Woonplaats:" + Woonplaats)
print("----------------------------------------------------")
